version: "3.9"

volumes:
  ex_mon_elixir:
      external: true
  pgadmin-data:
      external: true

services:
  db:
    image: postgis/postgis:14-3.2-alpine
    volumes:
      - ex_mon_elixir:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
